
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.udesc.servicos.entity;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-05-24T10:30:29.641-03:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "PedidoService",
                      portName = "PedidoServicePort",
                      targetNamespace = "http://entity.servicos.udesc.br/",
                      wsdlLocation = "http://localhost:8080/UDESCSoftServicosSOA/services/PedidoServicePort?wsdl",
                      endpointInterface = "br.udesc.servicos.entity.PedidoService")
                      
public class PedidoServiceImpl implements PedidoService {

    private static final Logger LOG = Logger.getLogger(PedidoServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see br.udesc.servicos.entity.PedidoService#alterarStatusPedido(int  codPedido ,)int  novoStatus )*
     */
    public void alterarStatusPedido(int codPedido,int novoStatus) { 
        LOG.info("Executing operation alterarStatusPedido");
        System.out.println(codPedido);
        System.out.println(novoStatus);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.udesc.servicos.entity.PedidoService#getPedido(int  codPedido )*
     */
    public br.udesc.servicos.entity.Pedido getPedido(int codPedido) { 
        LOG.info("Executing operation getPedido");
        System.out.println(codPedido);
        try {
            br.udesc.servicos.entity.Pedido _return = new br.udesc.servicos.entity.Pedido();
            _return.setCliente("Cliente-2051908173");
            _return.setCodigo(-1593206717);
            _return.setDataCadastro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-05-24T10:30:29.680-03:00"));
            _return.setDataEntrega(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-05-24T10:30:29.680-03:00"));
            java.util.List<br.udesc.servicos.entity.ItemPedido> _returnItens = new java.util.ArrayList<br.udesc.servicos.entity.ItemPedido>();
            br.udesc.servicos.entity.ItemPedido _returnItensVal1 = new br.udesc.servicos.entity.ItemPedido();
            br.udesc.servicos.entity.Produto _returnItensVal1Produto = new br.udesc.servicos.entity.Produto();
            _returnItensVal1Produto.setCodigo(1123597399);
            _returnItensVal1Produto.setDescricao("Descricao1168125570");
            _returnItensVal1Produto.setQuantidadeEstoque(-1243674077);
            _returnItensVal1Produto.setValorUnitario(0.3132020105388633);
            _returnItensVal1.setProduto(_returnItensVal1Produto);
            _returnItensVal1.setQuantidade(45537307);
            _returnItensVal1.setValorUnitario(0.35283881444905596);
            _returnItens.add(_returnItensVal1);
            _return.getItens().addAll(_returnItens);
            _return.setStatus(-221553069);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.udesc.servicos.entity.PedidoService#createPedido(br.udesc.servicos.entity.Pedido  pedido )*
     */
    public boolean createPedido(br.udesc.servicos.entity.Pedido pedido) { 
        LOG.info("Executing operation createPedido");
        System.out.println(pedido);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.udesc.servicos.entity.PedidoService#getPedidosPorStatus(int  codStatus )*
     */
    public java.util.List<br.udesc.servicos.entity.Pedido> getPedidosPorStatus(int codStatus) { 
        LOG.info("Executing operation getPedidosPorStatus");
        System.out.println(codStatus);
        try {
            java.util.List<br.udesc.servicos.entity.Pedido> _return = new java.util.ArrayList<br.udesc.servicos.entity.Pedido>();
            br.udesc.servicos.entity.Pedido _returnVal1 = new br.udesc.servicos.entity.Pedido();
            _returnVal1.setCliente("Cliente-403179784");
            _returnVal1.setCodigo(-1155060944);
            _returnVal1.setDataCadastro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-05-24T10:30:29.687-03:00"));
            _returnVal1.setDataEntrega(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-05-24T10:30:29.688-03:00"));
            java.util.List<br.udesc.servicos.entity.ItemPedido> _returnVal1Itens = new java.util.ArrayList<br.udesc.servicos.entity.ItemPedido>();
            br.udesc.servicos.entity.ItemPedido _returnVal1ItensVal1 = new br.udesc.servicos.entity.ItemPedido();
            br.udesc.servicos.entity.Produto _returnVal1ItensVal1Produto = new br.udesc.servicos.entity.Produto();
            _returnVal1ItensVal1Produto.setCodigo(-1635128979);
            _returnVal1ItensVal1Produto.setDescricao("Descricao881930157");
            _returnVal1ItensVal1Produto.setQuantidadeEstoque(-1763218042);
            _returnVal1ItensVal1Produto.setValorUnitario(0.14265828346467457);
            _returnVal1ItensVal1.setProduto(_returnVal1ItensVal1Produto);
            _returnVal1ItensVal1.setQuantidade(1734501154);
            _returnVal1ItensVal1.setValorUnitario(0.9587966899713692);
            _returnVal1Itens.add(_returnVal1ItensVal1);
            _returnVal1.getItens().addAll(_returnVal1Itens);
            _returnVal1.setStatus(-1937093396);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
